name: 'Setup Neosync CLI'
description: 'Setup Neosync CLI on Github Action runners'
author: 'nucleuscloud'

branding:
  icon: 'rocket'
  color: 'purple'

inputs:
  version:
    description: Version of Neosync CLI to install
    required: false
    default: latest

runs:
  using: node20
  main: dist/index.js
